# using - https://taskfile.dev/

version: "3"

# Task variables
vars:
  APPPATH: ./cmd/armv
  PROJECT_NAME: go-cli-starter #Change this to suit
  TARGET:
    sh: if [ "$(go env GOOS)" = "windows" ]; then echo "armv.exe"; else echo "armv"; fi

###########################################################################

tasks:
  ## release - Builds the project in preparation for (local)release
  release:
    deps: [lint]
    cmds:
      - go build -ldflags="-s -w" -o bin/{{.TARGET}} {{.APPPATH}}

  ###############################################################################

  ## goreleaser - Builds the project in preparation for release
  goreleaser:
    cmds:
      - goreleaser release --snapshot --clean

  ###############################################################################

  ## build - Builds the project in preparation for debug
  build:
    cmds:
      - go build -o bin/{{.TARGET}} {{.APPPATH}}

  ###############################################################################

  ## run - builds and runs the program on the target platform
  run:
    cmds:
      - go run {{.APPPATH}} --help

  ###############################################################################

  ## clean - Remove the old builds and any debug information
  clean:
    cmds:
      - go clean -cache
      - go clean
      - rm -rf dist bin
    platforms: [darwin, linux]
  clean_windows:
    silent: true
    cmds:
      - cmd /c "rmdir /s /q dist || exit 0"
      - cmd /c "rmdir /s /q bin || exit 0"
    platforms: [windows]

  ###############################################################################

  ## test - executes unit tests
  test:
    cmds:
      - go test -v ./...

  ###############################################################################

  ## deps - fetches any external dependencies and updates
  deps:
    cmds:
      - go mod tidy
      - go mod download
      - go get -u ./...

  ###############################################################################

  ## vet - Vet examines Go source code and reports suspicious constructs
  vet:
    cmds:
      - go vet ./...

  ###############################################################################

  ## staticcheck - Runs static code analyzer staticcheck
  staticcheck:
    cmds:
      - go run honnef.co/go/tools/cmd/staticcheck@latest ./...

  ###############################################################################

  ## seccheck - Code vulnerability check
  seccheck:
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  ###############################################################################

  ## lint - format code and tidy modules
  lint:
    cmds:
      - go fmt ./...
      - go mod tidy -v
      #- golangci-lint run ./...

  ###############################################################################

  ## generate - update build version
  generate:
    cmds:
      - go generate {{.APPPATH}}

  ###############################################################################
