name: test

on:
  push:
    branches:
      - "*"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.26.0"

      - name: Run tests
        run: go test -v ./...

      - name: Run staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...

      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
